export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCC_QUANTITY: "INCC_QUANTITY",
  DESC_QUANTITY: "DESC_QUANTITY",
  FILTER_BY_SEARCH: "FILTER_BY_SEARCH",
  SORT_BY_PRICE: "SORT_BY_PRICE",
  FILTER_BY_GARDEN:"FILTER_BY_GARDEN",
  FILTER_BY_INTERIOR:"FILTER_BY_INTERIOR",
  FILTER_BY_OFFICE:"FILTER_BY_OFFICE",
  CLEAR_FILTER:"CLEAR_FILTER",

};
